name: reading_tracker_v2
description: A new Flutter project based on a detailed database schema.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # API ve Veritabanı
  http: ^1.2.1 
  sqflite: ^2.3.0
  path_provider: ^2.1.1

  # State Management
  provider: ^6.0.5
  flutter_launcher_icons: ^0.14.4

  # Yardımcı Kütüphaneler
  intl: ^0.18.1
  cupertino_icons: ^1.0.2

  flutter_barcode_scanner: ^2.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Fontları uygulamaya eklemek için bu bölümü kullanın.
  # Girintilerin (boşlukların) doğru olduğundan emin olun.
  # 'fonts:' anahtarı 'flutter:' anahtarının altında iki boşluk içeride olmalıdır.
  fonts:
    - family: Georgia
      fonts:
        - asset: assets/fonts/georgia.ttf
        - asset: assets/fonts/georgiab.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
